---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: 3.8.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  valuesFrom:
    - kind: Secret
      name: loki-values
      valuesKey: values.yaml
