---
                                                              
apiVersion: v1
kind: Secret
metadata:
    name: loki-values
    namespace: logging
stringData:
    values.yaml: |
        loki:
          deploymentMode: SingleBinary
          commonConfig:
            replication_factor: 1
          storage:
            bucketNames:
              chunks: my-dev-loki-chunks
              ruler: my-dev-loki-ruler
              admin: my-dev-loki-admin
            type: s3
            s3:
              s3: s3.ru-1.storage.selcloud.ru
              endpoint: https://s3.ru-1.storage.selcloud.ru
              region: "ru-1"
              secretAccessKey: 
              accessKeyId: 
              s3ForcePathStyle: true
              insecure: false
