---
apiVersion: v1
kind: Secret
metadata:
    name: loki-values
    namespace: logging
stringData:
    values.yaml: |
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'