---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: net-prod-cert
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cert-manager
  path: "./infrastructure/context/certs"
  targetNamespace: production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
