---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-server
  namespace: nfsstorage
spec:
  interval: 10m
  chart:
    spec:
      chart: nfs-server-provisioner
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: nfsstorage-helm
        namespace: flux-system
      interval: 10m
  values:
    persistence:
      size: 1Gi
      enable: true
      storageClass: do-block-storage
