---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-net-crt
  namespace: production
spec:
  secretName: prod-net-crt
  commonName: "k8s-admin.ru"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - test.k8s-admin.ru"
