---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-net-crt-web
  namespace: production
spec:
  secretName: prod-net-crt-web
  commonName: "web.k8s-admin.ru"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - web.k8s-admin.ru"