---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-net-crt
  namespace: production
spec:
  secretName: prod-net-crt
  commonName: "test-test.my.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - test-test.my.com"
