---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfs
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/nfs/nfs/"
  targetNamespace: nfsstorage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
