---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-selectel
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager-webhook-selectel
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-selectel
        namespace: flux-system
      interval: 10m
  values:
    image:
      repository: ghcr.io/selectel/cert-manager-webhook-selectel
      tag: v1.3.0
      pullPolicy: IfNotPresent
