apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-webhook-selectel
  namespace: flux-system
spec:
  interval: 10m
  url: https://selectel.github.io/cert-manager-webhook-selectel
